env:
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "A"
  timeout_in: 120m
  container:
    image: ghcr.io/sushrut1101/docker:arch
    cpu: 8
    memory: 32G

  Build_script:
     - bash build.sh
